/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.marmeto.sproxiltnt;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f050001;
        public static final int blue=0x7f050004;
        public static final int brown=0x7f050008;
        public static final int darkblue=0x7f050009;
        public static final int darkgray=0x7f050003;
        public static final int gray=0x7f050002;
        public static final int green=0x7f050006;
        public static final int lightblue=0x7f05000a;
        public static final int purple=0x7f050007;
        public static final int red=0x7f050005;
        public static final int white=0x7f050000;
    }
    public static final class drawable {
        public static final int app_icon_tracktrace=0x7f020000;
        public static final int btn_default_normal=0x7f020001;
        public static final int btn_dropdown_normal=0x7f020002;
        public static final int btn_dropdown_white=0x7f020003;
        public static final int check=0x7f020004;
        public static final int editbox_background_normal=0x7f020005;
        public static final int gradient=0x7f020006;
        public static final int homebutton=0x7f020007;
        public static final int ic_launcher=0x7f020008;
        public static final int menubuttons=0x7f020009;
        public static final int pinfake=0x7f02000a;
        public static final int pinused=0x7f02000b;
        public static final int progress=0x7f02000c;
        public static final int roundedview=0x7f02000d;
        public static final int sproxilbutton=0x7f02000e;
        public static final int success=0x7f02000f;
    }
    public static final class id {
        public static final int AggregateButton=0x7f070038;
        public static final int ChangeEmailButton=0x7f070018;
        public static final int DeaggregateButton=0x7f070059;
        public static final int DestroyShipmentButton=0x7f070043;
        public static final int DestroyShipmentLayout=0x7f070042;
        public static final int DisassociateShipmentByDHLButton=0x7f07003d;
        public static final int DisassociateShipmentByTNTButton=0x7f07003f;
        public static final int ReaggregateButton=0x7f07005b;
        public static final int ReassociateShipmentButton=0x7f070041;
        public static final int ReassociateShipmentLayout=0x7f070040;
        public static final int SendReportButton=0x7f070045;
        public static final int UpdatePasswordButton=0x7f070016;
        public static final int UpdateSettingsButton=0x7f07001a;
        public static final int UploadReportButton=0x7f070057;
        public static final int addNoteEdit=0x7f070026;
        public static final int addNoteView=0x7f070025;
        public static final int addShipmentButton=0x7f070029;
        public static final int addTrackingEdit=0x7f070008;
        public static final int addTrackingView=0x7f070007;
        public static final int aggregateLayout=0x7f070037;
        public static final int aggregateMoreButton=0x7f070039;
        public static final int aggregatebutton=0x7f07001d;
        public static final int aggregatedcasenumberview=0x7f070049;
        public static final int aggregatednumberofcases=0x7f070048;
        public static final int assignDestinationButton=0x7f07003b;
        public static final int assignDestinationLayout=0x7f07003a;
        public static final int associateMoreButton=0x7f070021;
        public static final int bottom=0x7f07000c;
        public static final int carton=0x7f070010;
        public static final int cartonsscanned=0x7f07000f;
        public static final int changeEmailLayout=0x7f070017;
        public static final int confirmbutton=0x7f070013;
        public static final int deaggregateLayout=0x7f070058;
        public static final int deaggregatedcasenumberview=0x7f070054;
        public static final int deaggregatednumberofcases=0x7f070053;
        public static final int destination=0x7f070023;
        public static final int destinationlist=0x7f070024;
        public static final int destroyedshipments=0x7f070050;
        public static final int destroyedshipmentsnumber=0x7f070051;
        public static final int dhlTrackingNumber=0x7f070022;
        public static final int disassociateNowButton=0x7f07002d;
        public static final int disassociateShipmentButton=0x7f07003c;
        public static final int disassociateShipmentByTNTButton=0x7f07003e;
        public static final int disassociatebydhlnumber=0x7f07004b;
        public static final int disassociatedbydhl=0x7f07004a;
        public static final int disassociatedbytnt=0x7f07004c;
        public static final int disassociatedbytntnumber=0x7f07004d;
        public static final int editText1=0x7f070001;
        public static final int emailaddressview=0x7f070047;
        public static final int help=0x7f07000e;
        public static final int imageView1=0x7f070020;
        public static final int img=0x7f07002a;
        public static final int loginButton=0x7f070034;
        public static final int logout=0x7f07000d;
        public static final int mainSpinner1=0x7f07002e;
        public static final int mid=0x7f070009;
        public static final int newEmail1=0x7f07005c;
        public static final int newEmail2=0x7f07005e;
        public static final int newEmail3=0x7f070060;
        public static final int newEmailEdit1=0x7f07005d;
        public static final int newEmailEdit2=0x7f07005f;
        public static final int newEmailEdit3=0x7f070061;
        public static final int newPassConfirm=0x7f070066;
        public static final int newPasswordConfirmEdit=0x7f070067;
        public static final int newPasswordEdit=0x7f070065;
        public static final int newpass=0x7f070064;
        public static final int pass=0x7f070032;
        public static final int passwordEdit=0x7f070033;
        public static final int pin=0x7f070012;
        public static final int powerby=0x7f070036;
        public static final int reaggregateLayout=0x7f07005a;
        public static final int reaggregateNowButton=0x7f07002c;
        public static final int reassociatedsshipments=0x7f07004e;
        public static final int reassociatedsshipmentsnumber=0x7f07004f;
        public static final int result=0x7f07001c;
        public static final int resultList=0x7f070055;
        public static final int scanShipperCasesButton=0x7f07000a;
        public static final int scannedcartons=0x7f07001b;
        public static final int scrollView1=0x7f070004;
        public static final int sendReportButton=0x7f070052;
        public static final int sendReportLayout=0x7f070044;
        public static final int sendto=0x7f070046;
        public static final int shippersscanned=0x7f070028;
        public static final int textView1=0x7f07002f;
        public static final int textViewData=0x7f070000;
        public static final int textViewStatus=0x7f070003;
        public static final int textViewStatusTitle=0x7f070002;
        public static final int title=0x7f070006;
        public static final int tntpin=0x7f070011;
        public static final int top=0x7f070005;
        public static final int trackandtraceButton=0x7f07001e;
        public static final int txt=0x7f07002b;
        public static final int undo=0x7f07000b;
        public static final int undoall=0x7f07001f;
        public static final int updateButton=0x7f070062;
        public static final int updateDestinationButton=0x7f070027;
        public static final int updateEmail=0x7f070063;
        public static final int updatePasswordLayout=0x7f070015;
        public static final int updateRole=0x7f070068;
        public static final int updateSettingsLayout=0x7f070019;
        public static final int updatequeue=0x7f070014;
        public static final int uploadReportLayout=0x7f070056;
        public static final int userList=0x7f070031;
        public static final int username=0x7f070030;
        public static final int versionView=0x7f070035;
    }
    public static final class layout {
        public static final int activity_broadcast_intent=0x7f030000;
        public static final int activity_main=0x7f030001;
        public static final int add_dhl_number=0x7f030002;
        public static final int addlabel=0x7f030003;
        public static final int admin_main=0x7f030004;
        public static final int aggregate=0x7f030005;
        public static final int airbill_queue_success=0x7f030006;
        public static final int assign_destination=0x7f030007;
        public static final int associate_airbill=0x7f030008;
        public static final int customlist=0x7f030009;
        public static final int customspinner=0x7f03000a;
        public static final int deaggregate=0x7f03000b;
        public static final int deaggregate_shipper=0x7f03000c;
        public static final int disassociate_dhl=0x7f03000d;
        public static final int disassociate_tnt=0x7f03000e;
        public static final int list_single=0x7f03000f;
        public static final int loadingscreen=0x7f030010;
        public static final int login=0x7f030011;
        public static final int operator_main=0x7f030012;
        public static final int queuesuccess=0x7f030013;
        public static final int reaggregate=0x7f030014;
        public static final int reaggregationsuccess=0x7f030015;
        public static final int rxc_admin=0x7f030016;
        public static final int rxc_main=0x7f030017;
        public static final int scanlabel=0x7f030018;
        public static final int send_rxc_report=0x7f030019;
        public static final int sendreport=0x7f03001a;
        public static final int success=0x7f03001b;
        public static final int supervisor_main=0x7f03001c;
        public static final int update_email=0x7f03001d;
        public static final int update_shipment=0x7f03001e;
        public static final int updaterole=0x7f03001f;
    }
    public static final class string {
        public static final int adddestination=0x7f04008b;
        public static final int addnote=0x7f040093;
        public static final int addshipmentinfo=0x7f040037;
        public static final int addshipmenttoqueue=0x7f040082;
        public static final int addtrackandtrace=0x7f040036;
        public static final int addtracking=0x7f04008c;
        /**  PAGE TITLE STRINGS 
         */
        public static final int adminmain=0x7f040015;
        /**  OPERATOR STRINGS 
         */
        public static final int aggregate=0x7f040035;
        public static final int aggregatedcasenumber=0x7f040057;
        public static final int aggregatedcases=0x7f040054;
        public static final int aggregatelater=0x7f04005f;
        public static final int aggregatemore=0x7f04004b;
        public static final int aggregatenow=0x7f04005d;
        public static final int aggregatepage=0x7f04001f;
        public static final int airbillscannedtwice=0x7f040077;
        public static final int app_name=0x7f040000;
        public static final int applysettingspage=0x7f040023;
        /**  RXC STRINGS 
         */
        public static final int assigndestination=0x7f040080;
        public static final int assigndestinationcheck=0x7f040094;
        public static final int assigndestinationconfirm=0x7f040095;
        public static final int assigndestinationpage=0x7f040025;
        public static final int assignheader=0x7f040088;
        public static final int assignlabel=0x7f04008a;
        public static final int assigntrackingconfirm=0x7f04009c;
        /**  RXC SEND REPORT 
         */
        public static final int associatedshipments=0x7f040064;
        public static final int associatemore=0x7f04004c;
        public static final int associateshipment=0x7f04001b;
        public static final int associateshipmentinfo=0x7f040081;
        /**  PASWORD NOTIFICATION STRINGS 
         */
        public static final int attention=0x7f0400ae;
        /**  BACK REQUEST NOTIFICATION STRINGS 
         */
        public static final int backrequest=0x7f0400a8;
        public static final int backrequestconfirm=0x7f0400ab;
        public static final int backrequestreaggregateconfirm=0x7f0400ac;
        public static final int cancel=0x7f0400a3;
        public static final int carton=0x7f040045;
        public static final int cartonexists=0x7f04007e;
        public static final int cartonexists2=0x7f04007f;
        public static final int cartonsscanned=0x7f040043;
        public static final int casetest=0x7f040048;
        public static final int changeemail=0x7f040028;
        public static final int confirm=0x7f0400a2;
        public static final int confirmaggregate=0x7f040042;
        public static final int confirmupdatereport=0x7f04005c;
        public static final int copyright=0x7f040009;
        public static final int copyright2=0x7f04000a;
        public static final int currentemail=0x7f04002c;
        public static final int deaggregate=0x7f040051;
        public static final int deaggregatedcasenumber=0x7f040058;
        public static final int deaggregatedcases=0x7f040055;
        public static final int deaggregatenow=0x7f04005e;
        public static final int deaggregateok=0x7f040060;
        public static final int deaggregatepage=0x7f040020;
        public static final int deaggregatereconfirm=0x7f040063;
        public static final int descInput=0x7f040006;
        public static final int descScan=0x7f040005;
        public static final int destinationlist=0x7f040085;
        public static final int destroyconfirm=0x7f04009f;
        public static final int destroyedshipments=0x7f040068;
        public static final int destroyshipment=0x7f040091;
        public static final int disassociatedbydhl=0x7f040065;
        public static final int disassociatedbytnt=0x7f040066;
        public static final int disassociateshipment=0x7f04008f;
        public static final int disassociateshipmenttnt=0x7f040090;
        public static final int disassociationadd=0x7f040038;
        public static final int disassociationadd2=0x7f040039;
        public static final int disassociationconfirm=0x7f04009d;
        public static final int disassociationconfirm2=0x7f04009e;
        public static final int disassociationok=0x7f040061;
        public static final int disassociationok2=0x7f040062;
        public static final int emailaddress=0x7f040053;
        /**  EMAIL NOTIFICATION STRINGS 
         */
        public static final int emailchange=0x7f0400b1;
        public static final int emailchangeconfirm=0x7f0400b2;
        /**  ERROR STRINGS 
         */
        public static final int error=0x7f040069;
        public static final int fail=0x7f040073;
        public static final int helpDesc=0x7f040008;
        public static final int home=0x7f04000e;
        public static final int invalidcartonqr=0x7f040078;
        public static final int invalidemail=0x7f04006e;
        public static final int invalidemailformat=0x7f04006b;
        public static final int invalidpassword=0x7f04006a;
        public static final int invalidtntqr=0x7f040079;
        public static final int loadingscreen=0x7f04001e;
        public static final int login=0x7f04000d;
        public static final int logodesc=0x7f040003;
        public static final int logout=0x7f040034;
        public static final int logoutrequest=0x7f0400a9;
        public static final int logoutrequestconfirm=0x7f0400aa;
        public static final int maxcases=0x7f04006c;
        public static final int maxshippers=0x7f04006d;
        public static final int newemail1=0x7f04002d;
        public static final int newemail2=0x7f04002e;
        public static final int newemail3=0x7f04002f;
        public static final int newpass=0x7f040032;
        public static final int newpassconfirm=0x7f040033;
        public static final int newpasses_nonmatch=0x7f040070;
        public static final int no=0x7f0400a1;
        public static final int noconnection=0x7f040072;
        public static final int noconnectionemail=0x7f0400a5;
        public static final int noconnectionreports=0x7f0400a7;
        public static final int noconnectionsettings=0x7f0400a6;
        public static final int noconnectionupdatesettings=0x7f0400a4;
        public static final int noresponse=0x7f040074;
        public static final int operatormain=0x7f040017;
        public static final int passchange=0x7f0400af;
        public static final int passchangeconfirm=0x7f0400b0;
        public static final int password=0x7f040012;
        public static final int pin=0x7f040047;
        public static final int poweredby=0x7f040001;
        public static final int queuesuccess=0x7f040022;
        public static final int reaggregate=0x7f040050;
        public static final int reaggregatedcasenumber=0x7f040059;
        public static final int reaggregatedcases=0x7f040056;
        public static final int reassociatedsshipments=0x7f040067;
        public static final int reassociateshipment=0x7f040092;
        public static final int result=0x7f04000b;
        public static final int resultDesc=0x7f040007;
        public static final int returntomain=0x7f04004d;
        public static final int rolesuccess=0x7f040031;
        public static final int rxcadminmain=0x7f040019;
        public static final int rxcmain=0x7f040018;
        public static final int scanbutton=0x7f04000c;
        public static final int scanhelp=0x7f04003a;
        public static final int scanlabel=0x7f040086;
        public static final int scanlabelnow=0x7f040087;
        public static final int scanlabelpage=0x7f040021;
        public static final int scannedtwice=0x7f040076;
        public static final int scannererror=0x7f040075;
        public static final int scanorinput=0x7f040089;
        public static final int scanshippercases=0x7f040083;
        public static final int sendcaseconfirm=0x7f04004a;
        public static final int sendcaseok=0x7f040049;
        public static final int sendemailto=0x7f040052;
        public static final int sendreport=0x7f04005a;
        public static final int sendreportpage=0x7f040024;
        public static final int shipmentexists=0x7f04007c;
        public static final int shipmentnotfound=0x7f0400ad;
        public static final int shippercount=0x7f04008d;
        public static final int shippersscanned=0x7f040044;
        public static final int shippingcaseexists=0x7f04007b;
        public static final int shippingcaseexists2=0x7f04007d;
        public static final int sproxillogo=0x7f040004;
        public static final int submit=0x7f040014;
        public static final int successpage=0x7f04001d;
        public static final int supervisormain=0x7f040016;
        public static final int support=0x7f04000f;
        public static final int terms=0x7f040010;
        public static final int tntpin=0x7f040046;
        public static final int tntscannedtwice=0x7f04007a;
        public static final int tryagain=0x7f04006f;
        public static final int undo=0x7f04003b;
        public static final int undoAirbill=0x7f04003d;
        public static final int undoLast=0x7f04003e;
        public static final int undoall=0x7f04003f;
        public static final int undoallshippers=0x7f040040;
        public static final int undodhl=0x7f04003c;
        public static final int undoshipper=0x7f040041;
        public static final int updateFail=0x7f040071;
        public static final int updatedestinationbutton=0x7f04008e;
        public static final int updatedestinationcheck=0x7f040096;
        public static final int updatedestinationconfirm=0x7f040097;
        public static final int updatedestinationconfirm2=0x7f040098;
        public static final int updatedestinationconfirm3=0x7f040099;
        public static final int updatedestinationconfirm4=0x7f04009a;
        public static final int updatedestinationconfirm5=0x7f04009b;
        public static final int updateemail=0x7f040030;
        public static final int updateemailpage=0x7f04001c;
        /**  ADMIN STRINGS 
         */
        public static final int updatepassword=0x7f040027;
        public static final int updatereportalert=0x7f04005b;
        public static final int updaterole=0x7f04002a;
        public static final int updaterolepage=0x7f04001a;
        public static final int updaterolepass=0x7f04002b;
        public static final int updatesettings=0x7f040029;
        public static final int updateshipment=0x7f040084;
        public static final int updateshipmentpage=0x7f040026;
        /**  SUPERVISOR STRINGS 
         */
        public static final int uploadreport=0x7f04004f;
        public static final int userList=0x7f040013;
        public static final int username=0x7f040011;
        public static final int version=0x7f040002;
        /**  NOTIFICATION STRINGS 
         */
        public static final int yes=0x7f0400a0;
        public static final int zero=0x7f04004e;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
        public static final int OverlayDialog=0x7f060005;
        public static final int homebutton=0x7f060004;
        public static final int logoutbutton=0x7f060003;
        public static final int sproxilbutton=0x7f060002;
    }
}
